# Generated by Django 4.2.1 on 2023-05-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('project_name', models.CharField(max_length=30)),
                ('total_project_number', models.IntegerField(max_length=20)),
                ('project_description', models.TextField(max_length=300)),
            ],
        ),
    ]
